### ISSUE TITLE
Objective-C Support

### ISSUE THREAD

**Issue by codyd51** [MHaroonBaig/MotionKit#1]
Swift use is not available in all scenarios (such as tweak development, which is what I do), not to mention some people simply prefer Objective-C to Swift. I think this project could benefit from having ObjC support.

**Comment by MHaroonBaig** [comment]
Hello dear. Yes, I'll try to port it to Objective-C once I complete the Swift Version of the MotionKit. I'll keep this issue opened till then. I'd love if anyone wants to contribute and port it to Objective-C.

**Comment by codyd51** [comment]
Thanks! I wish I knew enough about CoreMotion to contribute directly, but nonetheless I look forward to being able to use MotionKit in my projects :smiley:

**Comment by DougFischer** [comment]
+1

**Comment by MHaroonBaig** [comment]
@codyd51 @DougFischer as promised, I've added ObjectiveC support to my MotionKit. You can now make all the function calls, if you install MotionKit through CocoaPods or Carthage. I've update the Readme to include Objective-C function calls as well. Have a look at them.

**Comment by codyd51** [comment]
Awesome, thanks so much for your work! 

I look forward to being able to use MotionKit in my works :)

Thanks again!
