### ISSUE TITLE
Objective C bridge

### ISSUE THREAD

**Issue by Tintenklecks** [MHaroonBaig/MotionKit#2]
When including 
# import "(mymodel)-swift.h"

the generated header includes just the delegate methods.

Adding the @objc in front of the swift methods doesn't work as it interferes with public

could you provide an Objective C sample (I know you´ve written a lot in the realm but I can't instantiate the object ;-)

**Comment by MHaroonBaig** [comment]
Sure, Let me provide you a snippet. 

#import "ViewController.h"
#import  < MotionKit/MotionKit-Swift.h >

@interface ViewController ()

@end

@implementation ViewController
- (void)viewDidLoad {
  [super viewDidLoad];
  MotionKit *motionKit = [[NSClassFromString(@"MotionKit") alloc] init];
  [motionKit getAccelerometerValuesWithInterval:1.0 values:^(double x, double y, double z) {
      printf("%f", x);
  }];
  [motionKit getAttitudeFromDeviceMotionWithInterval:1.0 values:^(CMAttitude *attitude) {
      // Your values here
  }];
  
  [motionKit getAccelerationAtCurrentInstant:^(double x, double y, double z) {
      //Your values here
  }];
  [motionKit getDeviceMotionObjectWithInterval:1.0 values:^(CMDeviceMotion *deviceMotion) {
      // Your values here
  }];
  // Do any additional setup after loading the view, typically from a nib.
  }
- (void)didReceiveMemoryWarning {
  [super didReceiveMemoryWarning];
  // Dispose of any resources that can be recreated.
  }

@end

**Comment by MHaroonBaig** [comment]
Its a ViewController.m file. Let me know if you need any help. Don't forget to send me the Log.

**Comment by MHaroonBaig** [comment]
Added the Objective-C example. Have a look.

**Comment by Tintenklecks** [comment]
Wooohooo ;-)

Thank you! 

killed two birds with one stone
1) Understood the bridging between swift and objc (I code objc too long to change that quick ;-)
2) got the accelerometer & co in the way I wished apple had implemented it

Thanks a lot

**Comment by MHaroonBaig** [comment]
I'm happy that it solved your problem :+1:
